[package]
name = "lit_math"
version = "0.1.0"
edition = "2021"

[build]
rustflags = "-C target-cpu=native -O"

[dependencies]


[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"
approx = "0.5.1"
statrs = "0.16"

[[bench]]
name = "bmk"
harness = false
path = "benches/bmk.rs"