[package]
name = "lit_math"
version = "0.1.0"
edition = "2021"

[build]
rustflags = "-C target-cpu=native -O"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "exp_benchmark"
harness = false
path = "benches/exp_benchmark.rs"